
import dns from "dns";
import dotenv from "dotenv";
import mongoose from "mongoose";
import Product from "./models/Product.js";

dotenv.config();
dns.setServers(["1.1.1.1"]);
const products = [
  // =========================
  // iPHONES / APPLE
  // =========================
  {
    name: "iPhone 15",
    brand: "Apple",
    category: "Smartphones",
    condition: "new",
    description: "Apple iPhone with powerful performance and advanced camera system.",
    price: 69999,
    originalPrice: 79999,
    stock: 15,
    rating: 4.8,
  },
  {
    name: "iPhone 15 Pro",
    brand: "Apple",
    category: "Smartphones",
    condition: "new",
    description: "Premium Apple smartphone with Pro camera system and titanium design.",
    price: 119999,
    originalPrice: 134999,
    stock: 10,
    rating: 4.9,
  },
  {
    name: "iPhone 13",
    brand: "Apple",
    category: "Smartphones",
    condition: "refurbished",
    description: "Reliable Apple smartphone with excellent camera and smooth performance.",
    price: 49999,
    originalPrice: 64999,
    stock: 12,
    rating: 4.7,
  },
  {
    name: "iPhone 13 Pro Max",
    brand: "Apple",
    category: "Smartphones",
    condition: "refurbished",
    description: "Large-display iPhone with premium camera performance and long battery life.",
    price: 65999,
    originalPrice: 89999,
    stock: 8,
    rating: 4.8,
  },
  {
    name: "iPhone 14",
    brand: "Apple",
    category: "Smartphones",
    condition: "new",
    description: "Premium Apple smartphone with Super Retina display and advanced photography.",
    price: 59999,
    originalPrice: 69999,
    stock: 11,
    rating: 4.7,
  },

  // =========================
  // SAMSUNG
  // =========================
  {
    name: "Samsung Galaxy S24",
    brand: "Samsung",
    category: "Smartphones",
    condition: "new",
    description: "Samsung flagship smartphone with powerful processor and advanced cameras.",
    price: 74999,
    originalPrice: 84999,
    stock: 14,
    rating: 4.8,
  },
  {
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    category: "Smartphones",
    condition: "new",
    description: "Premium Samsung flagship with S Pen, powerful cameras, and large display.",
    price: 109999,
    originalPrice: 129999,
    stock: 9,
    rating: 4.9,
  },
  {
    name: "Samsung Galaxy A55",
    brand: "Samsung",
    category: "Smartphones",
    condition: "new",
    description: "Mid-range Samsung smartphone with AMOLED display and strong battery life.",
    price: 39999,
    originalPrice: 45999,
    stock: 18,
    rating: 4.6,
  },
  {
    name: "Samsung Galaxy M35",
    brand: "Samsung",
    category: "Smartphones",
    condition: "new",
    description: "Affordable Samsung smartphone focused on battery life and everyday performance.",
    price: 18999,
    originalPrice: 21999,
    stock: 20,
    rating: 4.5,
  },
  {
    name: "Samsung Galaxy Tab S9 FE",
    brand: "Samsung",
    category: "Tablets",
    condition: "new",
    description: "Versatile Samsung tablet with bright display and S Pen support.",
    price: 36999,
    originalPrice: 42999,
    stock: 10,
    rating: 4.7,
  },

  // =========================
  // ONEPLUS
  // =========================
  {
    name: "OnePlus 12",
    brand: "OnePlus",
    category: "Smartphones",
    condition: "new",
    description: "High-performance OnePlus smartphone with flagship hardware and fast charging.",
    price: 64999,
    originalPrice: 74999,
    stock: 13,
    rating: 4.8,
  },
  {
    name: "OnePlus 12R",
    brand: "OnePlus",
    category: "Smartphones",
    condition: "new",
    description: "Performance-focused OnePlus smartphone with smooth display and fast charging.",
    price: 39999,
    originalPrice: 44999,
    stock: 16,
    rating: 4.7,
  },
  {
    name: "OnePlus Nord CE 4",
    brand: "OnePlus",
    category: "Smartphones",
    condition: "new",
    description: "Affordable OnePlus phone with strong performance and long battery life.",
    price: 24999,
    originalPrice: 27999,
    stock: 22,
    rating: 4.6,
  },
  {
    name: "OnePlus Nord 4",
    brand: "OnePlus",
    category: "Smartphones",
    condition: "new",
    description: "Premium mid-range OnePlus smartphone with metal design and fast charging.",
    price: 29999,
    originalPrice: 34999,
    stock: 17,
    rating: 4.7,
  },

  // =========================
  // OPPO
  // =========================
  {
    name: "OPPO Reno 11",
    brand: "OPPO",
    category: "Smartphones",
    condition: "new",
    description: "Stylish OPPO smartphone with portrait photography and fast charging.",
    price: 34999,
    originalPrice: 39999,
    stock: 14,
    rating: 4.6,
  },
  {
    name: "OPPO Reno 12",
    brand: "OPPO",
    category: "Smartphones",
    condition: "new",
    description: "Modern OPPO smartphone with AI features, smooth display, and fast charging.",
    price: 37999,
    originalPrice: 42999,
    stock: 15,
    rating: 4.7,
  },
  {
    name: "OPPO A79",
    brand: "OPPO",
    category: "Smartphones",
    condition: "new",
    description: "Affordable OPPO phone designed for everyday performance and entertainment.",
    price: 17999,
    originalPrice: 20999,
    stock: 20,
    rating: 4.5,
  },
  {
    name: "OPPO F25 Pro",
    brand: "OPPO",
    category: "Smartphones",
    condition: "refurbished",
    description: "Slim OPPO smartphone with AMOLED display and capable camera setup.",
    price: 24999,
    originalPrice: 29999,
    stock: 8,
    rating: 4.5,
  },

  // =========================
  // VIVO
  // =========================
  {
    name: "Vivo V30",
    brand: "Vivo",
    category: "Smartphones",
    condition: "new",
    description: "Elegant Vivo smartphone with portrait photography and bright AMOLED display.",
    price: 33999,
    originalPrice: 39999,
    stock: 15,
    rating: 4.7,
  },
  {
    name: "Vivo V40",
    brand: "Vivo",
    category: "Smartphones",
    condition: "new",
    description: "Camera-focused Vivo smartphone with premium design and fast charging.",
    price: 38999,
    originalPrice: 44999,
    stock: 13,
    rating: 4.7,
  },
  {
    name: "Vivo T3",
    brand: "Vivo",
    category: "Smartphones",
    condition: "new",
    description: "Performance-focused Vivo smartphone for gaming and daily use.",
    price: 21999,
    originalPrice: 24999,
    stock: 19,
    rating: 4.5,
  },
  {
    name: "Vivo Y200",
    brand: "Vivo",
    category: "Smartphones",
    condition: "new",
    description: "Value-focused Vivo phone with AMOLED display and long battery life.",
    price: 23999,
    originalPrice: 26999,
    stock: 18,
    rating: 4.5,
  },

  // =========================
  // GOOGLE
  // =========================
  {
    name: "Google Pixel 8",
    brand: "Google",
    category: "Smartphones",
    condition: "new",
    description: "Google Pixel smartphone with computational photography and clean Android.",
    price: 58999,
    originalPrice: 69999,
    stock: 9,
    rating: 4.8,
  },
  {
    name: "Google Pixel 8 Pro",
    brand: "Google",
    category: "Smartphones",
    condition: "new",
    description: "Premium Google Pixel with advanced cameras and AI-powered features.",
    price: 89999,
    originalPrice: 99999,
    stock: 7,
    rating: 4.9,
  },

  // =========================
  // LAPTOPS
  // =========================
  {
    name: "HP Pavilion 14",
    brand: "HP",
    category: "Laptops",
    condition: "new",
    description: "Everyday laptop for students, work, browsing, and productivity.",
    price: 62999,
    originalPrice: 69999,
    stock: 10,
    rating: 4.5,
  },
  {
    name: "Lenovo IdeaPad Slim 5",
    brand: "Lenovo",
    category: "Laptops",
    condition: "new",
    description: "Slim productivity laptop with strong performance and portability.",
    price: 67999,
    originalPrice: 74999,
    stock: 9,
    rating: 4.6,
  },
  {
    name: "Dell Inspiron 15",
    brand: "Dell",
    category: "Laptops",
    condition: "refurbished",
    description: "Reliable Dell laptop suitable for study, office work, and daily use.",
    price: 49999,
    originalPrice: 59999,
    stock: 8,
    rating: 4.5,
  },
    // =========================
  // ADDITIONAL iPHONES
  // =========================
  {
    name: "iPhone 12",
    brand: "Apple",
    category: "Smartphones",
    condition: "refurbished",
    description: "Popular Apple smartphone with reliable performance and dual camera system.",
    price: 39999,
    originalPrice: 54999,
    stock: 10,
    rating: 4.6,
  },
  {
    name: "iPhone 12 Pro",
    brand: "Apple",
    category: "Smartphones",
    condition: "refurbished",
    description: "Premium Apple smartphone with Pro camera system and stainless steel design.",
    price: 48999,
    originalPrice: 69999,
    stock: 8,
    rating: 4.7,
  },
  {
    name: "iPhone 14 Plus",
    brand: "Apple",
    category: "Smartphones",
    condition: "new",
    description: "Large-screen Apple smartphone with powerful performance and long battery life.",
    price: 69999,
    originalPrice: 79999,
    stock: 9,
    rating: 4.7,
  },
  {
    name: "iPhone 15 Plus",
    brand: "Apple",
    category: "Smartphones",
    condition: "new",
    description: "Large-display Apple smartphone with modern design and advanced cameras.",
    price: 79999,
    originalPrice: 89999,
    stock: 8,
    rating: 4.8,
  },
  {
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    category: "Smartphones",
    condition: "new",
    description: "Premium Apple flagship with large display, Pro cameras, and titanium design.",
    price: 134999,
    originalPrice: 149999,
    stock: 6,
    rating: 4.9,
  },
  {
    name: "iPhone 16",
    brand: "Apple",
    category: "Smartphones",
    condition: "new",
    description: "Modern Apple smartphone with advanced performance and camera features.",
    price: 79999,
    originalPrice: 89999,
    stock: 10,
    rating: 4.8,
  },

  // =========================
  // ADDITIONAL SAMSUNG
  // =========================
  {
    name: "Samsung Galaxy S23",
    brand: "Samsung",
    category: "Smartphones",
    condition: "refurbished",
    description: "Compact Samsung flagship with excellent cameras and smooth performance.",
    price: 54999,
    originalPrice: 74999,
    stock: 10,
    rating: 4.7,
  },
  {
    name: "Samsung Galaxy S23 Plus",
    brand: "Samsung",
    category: "Smartphones",
    condition: "refurbished",
    description: "Premium Samsung smartphone with large display and flagship performance.",
    price: 64999,
    originalPrice: 84999,
    stock: 8,
    rating: 4.8,
  },
  {
    name: "Samsung Galaxy S22",
    brand: "Samsung",
    category: "Smartphones",
    condition: "refurbished",
    description: "Flagship Samsung smartphone with compact design and advanced cameras.",
    price: 44999,
    originalPrice: 59999,
    stock: 9,
    rating: 4.6,
  },
  {
    name: "Samsung Galaxy A35",
    brand: "Samsung",
    category: "Smartphones",
    condition: "new",
    description: "Samsung mid-range smartphone with AMOLED display and dependable battery life.",
    price: 29999,
    originalPrice: 34999,
    stock: 16,
    rating: 4.5,
  },
  {
    name: "Samsung Galaxy A25",
    brand: "Samsung",
    category: "Smartphones",
    condition: "new",
    description: "Affordable Samsung smartphone for everyday use and entertainment.",
    price: 21999,
    originalPrice: 24999,
    stock: 18,
    rating: 4.5,
  },

  // =========================
  // ADDITIONAL ONEPLUS
  // =========================
  {
    name: "OnePlus 11",
    brand: "OnePlus",
    category: "Smartphones",
    condition: "refurbished",
    description: "Former OnePlus flagship with powerful performance and fast charging.",
    price: 44999,
    originalPrice: 59999,
    stock: 9,
    rating: 4.7,
  },
  {
    name: "OnePlus 10 Pro",
    brand: "OnePlus",
    category: "Smartphones",
    condition: "refurbished",
    description: "Premium OnePlus smartphone with flagship cameras and smooth display.",
    price: 39999,
    originalPrice: 54999,
    stock: 8,
    rating: 4.6,
  },
  {
    name: "OnePlus Nord 3",
    brand: "OnePlus",
    category: "Smartphones",
    condition: "new",
    description: "Performance-focused OnePlus phone with AMOLED display and fast charging.",
    price: 27999,
    originalPrice: 32999,
    stock: 15,
    rating: 4.6,
  },
  {
    name: "OnePlus Nord CE 3",
    brand: "OnePlus",
    category: "Smartphones",
    condition: "new",
    description: "Affordable OnePlus smartphone with smooth display and strong battery life.",
    price: 21999,
    originalPrice: 25999,
    stock: 18,
    rating: 4.5,
  },
  {
    name: "OnePlus Nord CE 3 Lite",
    brand: "OnePlus",
    category: "Smartphones",
    condition: "new",
    description: "Budget-friendly OnePlus phone for everyday performance and entertainment.",
    price: 16999,
    originalPrice: 19999,
    stock: 20,
    rating: 4.4,
  },
  {
    name: "OnePlus 9 Pro",
    brand: "OnePlus",
    category: "Smartphones",
    condition: "refurbished",
    description: "Premium refurbished OnePlus flagship with high-end camera performance.",
    price: 29999,
    originalPrice: 44999,
    stock: 7,
    rating: 4.5,
  },
  {
    name: "OnePlus 8T",
    brand: "OnePlus",
    category: "Smartphones",
    condition: "refurbished",
    description: "Reliable OnePlus smartphone with smooth display and fast charging.",
    price: 19999,
    originalPrice: 29999,
    stock: 6,
    rating: 4.4,
  },

  // =========================
  // ADDITIONAL OPPO
  // =========================
  {
    name: "OPPO Reno 10",
    brand: "OPPO",
    category: "Smartphones",
    condition: "new",
    description: "Stylish OPPO smartphone with portrait photography and AMOLED display.",
    price: 28999,
    originalPrice: 34999,
    stock: 12,
    rating: 4.6,
  },
  {
    name: "OPPO Reno 10 Pro",
    brand: "OPPO",
    category: "Smartphones",
    condition: "new",
    description: "Premium OPPO smartphone with advanced portrait camera and fast charging.",
    price: 37999,
    originalPrice: 44999,
    stock: 9,
    rating: 4.7,
  },
  {
    name: "OPPO F27 Pro",
    brand: "OPPO",
    category: "Smartphones",
    condition: "new",
    description: "Feature-rich OPPO phone with premium design and excellent display.",
    price: 29999,
    originalPrice: 34999,
    stock: 13,
    rating: 4.6,
  },
  {
    name: "OPPO F25",
    brand: "OPPO",
    category: "Smartphones",
    condition: "new",
    description: "Slim OPPO smartphone with AMOLED display and capable cameras.",
    price: 23999,
    originalPrice: 27999,
    stock: 15,
    rating: 4.5,
  },
  {
    name: "OPPO A98",
    brand: "OPPO",
    category: "Smartphones",
    condition: "new",
    description: "Affordable OPPO smartphone with good battery life and everyday performance.",
    price: 21999,
    originalPrice: 24999,
    stock: 17,
    rating: 4.5,
  },
  {
    name: "OPPO A78",
    brand: "OPPO",
    category: "Smartphones",
    condition: "new",
    description: "Value-oriented OPPO smartphone for everyday communication and entertainment.",
    price: 17999,
    originalPrice: 20999,
    stock: 19,
    rating: 4.4,
  },
  {
    name: "OPPO A59",
    brand: "OPPO",
    category: "Smartphones",
    condition: "new",
    description: "Affordable 5G OPPO smartphone with dependable daily performance.",
    price: 15999,
    originalPrice: 18999,
    stock: 20,
    rating: 4.4,
  },
  {
    name: "OPPO Reno 8",
    brand: "OPPO",
    category: "Smartphones",
    condition: "refurbished",
    description: "Refurbished OPPO smartphone with strong cameras and premium styling.",
    price: 22999,
    originalPrice: 32999,
    stock: 8,
    rating: 4.5,
  },

  // =========================
  // ADDITIONAL VIVO
  // =========================
  {
    name: "Vivo V29",
    brand: "Vivo",
    category: "Smartphones",
    condition: "refurbished",
    description: "Camera-focused Vivo smartphone with curved AMOLED display.",
    price: 29999,
    originalPrice: 39999,
    stock: 8,
    rating: 4.6,
  },
  {
    name: "Vivo V29 Pro",
    brand: "Vivo",
    category: "Smartphones",
    condition: "new",
    description: "Premium Vivo smartphone with portrait photography and fast charging.",
    price: 37999,
    originalPrice: 44999,
    stock: 10,
    rating: 4.7,
  },
  {
    name: "Vivo V27",
    brand: "Vivo",
    category: "Smartphones",
    condition: "refurbished",
    description: "Stylish Vivo smartphone with AMOLED display and portrait camera.",
    price: 26999,
    originalPrice: 34999,
    stock: 9,
    rating: 4.6,
  },
  {
    name: "Vivo T2",
    brand: "Vivo",
    category: "Smartphones",
    condition: "new",
    description: "Performance-oriented Vivo smartphone with smooth display and fast charging.",
    price: 18999,
    originalPrice: 21999,
    stock: 18,
    rating: 4.4,
  },
  {
    name: "Vivo T3x",
    brand: "Vivo",
    category: "Smartphones",
    condition: "new",
    description: "Affordable Vivo smartphone with strong battery and daily performance.",
    price: 14999,
    originalPrice: 17999,
    stock: 20,
    rating: 4.4,
  },
  {
    name: "Vivo Y100",
    brand: "Vivo",
    category: "Smartphones",
    condition: "new",
    description: "Stylish Vivo smartphone with AMOLED display and good cameras.",
    price: 24999,
    originalPrice: 29999,
    stock: 14,
    rating: 4.5,
  },
  {
    name: "Vivo Y200 Pro",
    brand: "Vivo",
    category: "Smartphones",
    condition: "new",
    description: "Premium mid-range Vivo phone with curved display and fast charging.",
    price: 27999,
    originalPrice: 32999,
    stock: 12,
    rating: 4.6,
  },
  {
    name: "Vivo Y27",
    brand: "Vivo",
    category: "Smartphones",
    condition: "new",
    description: "Affordable Vivo smartphone for everyday communication and entertainment.",
    price: 16999,
    originalPrice: 19999,
    stock: 17,
    rating: 4.4,
  },

  // =========================
  // ACCESSORIES
  // =========================
  {
    name: "Apple AirPods Pro",
    brand: "Apple",
    category: "Accessories",
    condition: "new",
    description: "Premium wireless earbuds with active noise cancellation.",
    price: 19999,
    originalPrice: 24999,
    stock: 15,
    rating: 4.8,
  },
  {
    name: "OnePlus Buds 3",
    brand: "OnePlus",
    category: "Headphones",
    condition: "new",
    description: "Wireless earbuds with immersive sound and active noise cancellation.",
    price: 5499,
    originalPrice: 6999,
    stock: 20,
    rating: 4.6,
  },
  // =========================
// MORE APPLE iPHONES
// =========================
{
  name: "iPhone 12",
  brand: "Apple",
  category: "Smartphones",
  condition: "refurbished",
  description: "Reliable Apple smartphone with strong performance and excellent camera.",
  price: 39999,
  originalPrice: 49999,
  stock: 12,
  rating: 4.6,
},
{
  name: "iPhone 12 Pro",
  brand: "Apple",
  category: "Smartphones",
  condition: "refurbished",
  description: "Premium Apple smartphone with Pro camera capabilities.",
  price: 46999,
  originalPrice: 59999,
  stock: 10,
  rating: 4.7,
},
{
  name: "iPhone 12 Pro Max",
  brand: "Apple",
  category: "Smartphones",
  condition: "refurbished",
  description: "Large premium iPhone with advanced cameras and long battery life.",
  price: 52999,
  originalPrice: 69999,
  stock: 8,
  rating: 4.7,
},
{
  name: "iPhone 11",
  brand: "Apple",
  category: "Smartphones",
  condition: "refurbished",
  description: "Popular Apple smartphone with dual camera system.",
  price: 32999,
  originalPrice: 44999,
  stock: 14,
  rating: 4.5,
},
{
  name: "iPhone 11 Pro",
  brand: "Apple",
  category: "Smartphones",
  condition: "refurbished",
  description: "Compact premium iPhone with Pro camera system.",
  price: 37999,
  originalPrice: 49999,
  stock: 9,
  rating: 4.6,
},
{
  name: "iPhone SE 2022",
  brand: "Apple",
  category: "Smartphones",
  condition: "refurbished",
  description: "Compact Apple smartphone with strong performance.",
  price: 29999,
  originalPrice: 39999,
  stock: 13,
  rating: 4.5,
},

// =========================
// MORE SAMSUNG
// =========================
{
  name: "Samsung Galaxy S23",
  brand: "Samsung",
  category: "Smartphones",
  condition: "refurbished",
  description: "Samsung flagship smartphone with premium display and cameras.",
  price: 54999,
  originalPrice: 69999,
  stock: 12,
  rating: 4.7,
},
{
  name: "Samsung Galaxy S23 Plus",
  brand: "Samsung",
  category: "Smartphones",
  condition: "refurbished",
  description: "Large Samsung flagship with excellent display and battery life.",
  price: 62999,
  originalPrice: 79999,
  stock: 9,
  rating: 4.7,
},
{
  name: "Samsung Galaxy S22",
  brand: "Samsung",
  category: "Smartphones",
  condition: "refurbished",
  description: "Compact Samsung flagship with powerful performance.",
  price: 39999,
  originalPrice: 54999,
  stock: 10,
  rating: 4.6,
},
{
  name: "Samsung Galaxy A35",
  brand: "Samsung",
  category: "Smartphones",
  condition: "new",
  description: "Balanced Samsung smartphone for everyday use.",
  price: 29999,
  originalPrice: 34999,
  stock: 16,
  rating: 4.5,
},
{
  name: "Samsung Galaxy A25",
  brand: "Samsung",
  category: "Smartphones",
  condition: "new",
  description: "Affordable Samsung phone with AMOLED display and strong battery.",
  price: 21999,
  originalPrice: 24999,
  stock: 18,
  rating: 4.5,
},
{
  name: "Samsung Galaxy M55",
  brand: "Samsung",
  category: "Smartphones",
  condition: "new",
  description: "Performance-focused Samsung smartphone with fast charging.",
  price: 26999,
  originalPrice: 29999,
  stock: 17,
  rating: 4.6,
},

// =========================
// MORE ONEPLUS
// =========================
{
  name: "OnePlus 11",
  brand: "OnePlus",
  category: "Smartphones",
  condition: "refurbished",
  description: "Previous-generation OnePlus flagship with strong performance.",
  price: 49999,
  originalPrice: 64999,
  stock: 9,
  rating: 4.7,
},
{
  name: "OnePlus 11R",
  brand: "OnePlus",
  category: "Smartphones",
  condition: "refurbished",
  description: "High-performance OnePlus smartphone with fast charging.",
  price: 32999,
  originalPrice: 39999,
  stock: 12,
  rating: 4.6,
},
{
  name: "OnePlus Nord 3",
  brand: "OnePlus",
  category: "Smartphones",
  condition: "refurbished",
  description: "Powerful mid-range OnePlus phone for everyday performance.",
  price: 27999,
  originalPrice: 34999,
  stock: 15,
  rating: 4.6,
},
{
  name: "OnePlus Nord CE 3",
  brand: "OnePlus",
  category: "Smartphones",
  condition: "refurbished",
  description: "Affordable OnePlus smartphone with fast charging.",
  price: 19999,
  originalPrice: 24999,
  stock: 14,
  rating: 4.5,
},
{
  name: "OnePlus Nord CE 3 Lite",
  brand: "OnePlus",
  category: "Smartphones",
  condition: "new",
  description: "Budget-friendly OnePlus smartphone for daily use.",
  price: 16999,
  originalPrice: 19999,
  stock: 20,
  rating: 4.4,
},
{
  name: "OnePlus Nord 2T",
  brand: "OnePlus",
  category: "Smartphones",
  condition: "refurbished",
  description: "Smooth and fast OnePlus smartphone with capable cameras.",
  price: 21999,
  originalPrice: 29999,
  stock: 11,
  rating: 4.5,
},
{
  name: "OnePlus 10 Pro",
  brand: "OnePlus",
  category: "Smartphones",
  condition: "refurbished",
  description: "Premium OnePlus flagship with fast performance and charging.",
  price: 39999,
  originalPrice: 59999,
  stock: 7,
  rating: 4.6,
},
{
  name: "OnePlus 10T",
  brand: "OnePlus",
  category: "Smartphones",
  condition: "refurbished",
  description: "Performance-focused OnePlus device with rapid charging.",
  price: 29999,
  originalPrice: 39999,
  stock: 10,
  rating: 4.5,
},

// =========================
// MORE OPPO
// =========================
{
  name: "OPPO Reno 10",
  brand: "OPPO",
  category: "Smartphones",
  condition: "refurbished",
  description: "Stylish OPPO smartphone with portrait-focused camera system.",
  price: 27999,
  originalPrice: 34999,
  stock: 13,
  rating: 4.5,
},
{
  name: "OPPO Reno 10 Pro",
  brand: "OPPO",
  category: "Smartphones",
  condition: "refurbished",
  description: "Premium OPPO smartphone with advanced portrait photography.",
  price: 39999,
  originalPrice: 49999,
  stock: 8,
  rating: 4.7,
},
{
  name: "OPPO Reno 8",
  brand: "OPPO",
  category: "Smartphones",
  condition: "refurbished",
  description: "Camera-focused OPPO smartphone with premium design.",
  price: 22999,
  originalPrice: 32999,
  stock: 11,
  rating: 4.5,
},
{
  name: "OPPO F27 Pro",
  brand: "OPPO",
  category: "Smartphones",
  condition: "new",
  description: "Stylish OPPO smartphone with premium display and cameras.",
  price: 32999,
  originalPrice: 37999,
  stock: 12,
  rating: 4.6,
},
{
  name: "OPPO F23",
  brand: "OPPO",
  category: "Smartphones",
  condition: "refurbished",
  description: "Affordable OPPO smartphone with smooth performance.",
  price: 20999,
  originalPrice: 25999,
  stock: 15,
  rating: 4.5,
},
{
  name: "OPPO A78",
  brand: "OPPO",
  category: "Smartphones",
  condition: "new",
  description: "Value-oriented OPPO phone for everyday use.",
  price: 16999,
  originalPrice: 19999,
  stock: 18,
  rating: 4.4,
},
{
  name: "OPPO A59",
  brand: "OPPO",
  category: "Smartphones",
  condition: "new",
  description: "Affordable OPPO phone with reliable daily performance.",
  price: 14999,
  originalPrice: 17999,
  stock: 20,
  rating: 4.3,
},
{
  name: "OPPO A98",
  brand: "OPPO",
  category: "Smartphones",
  condition: "refurbished",
  description: "Mid-range OPPO phone with strong battery and smooth display.",
  price: 18999,
  originalPrice: 22999,
  stock: 14,
  rating: 4.4,
},

// =========================
// MORE VIVO
// =========================
{
  name: "Vivo V29",
  brand: "Vivo",
  category: "Smartphones",
  condition: "refurbished",
  description: "Vivo smartphone with portrait photography and AMOLED display.",
  price: 29999,
  originalPrice: 36999,
  stock: 12,
  rating: 4.6,
},
{
  name: "Vivo V27",
  brand: "Vivo",
  category: "Smartphones",
  condition: "refurbished",
  description: "Stylish Vivo smartphone with excellent portrait photography.",
  price: 26999,
  originalPrice: 34999,
  stock: 10,
  rating: 4.5,
},
{
  name: "Vivo V25",
  brand: "Vivo",
  category: "Smartphones",
  condition: "refurbished",
  description: "Slim Vivo smartphone with capable cameras and AMOLED display.",
  price: 22999,
  originalPrice: 29999,
  stock: 9,
  rating: 4.4,
},
{
  name: "Vivo T2",
  brand: "Vivo",
  category: "Smartphones",
  condition: "refurbished",
  description: "Performance-focused Vivo smartphone for daily use and gaming.",
  price: 17999,
  originalPrice: 21999,
  stock: 16,
  rating: 4.4,
},
{
  name: "Vivo T2 Pro",
  brand: "Vivo",
  category: "Smartphones",
  condition: "new",
  description: "Fast Vivo smartphone with AMOLED display and strong performance.",
  price: 22999,
  originalPrice: 26999,
  stock: 14,
  rating: 4.5,
},
{
  name: "Vivo Y100",
  brand: "Vivo",
  category: "Smartphones",
  condition: "new",
  description: "Affordable Vivo phone with stylish design and AMOLED display.",
  price: 23999,
  originalPrice: 27999,
  stock: 17,
  rating: 4.4,
},
{
  name: "Vivo Y200e",
  brand: "Vivo",
  category: "Smartphones",
  condition: "new",
  description: "Value-focused Vivo smartphone with long battery life.",
  price: 19999,
  originalPrice: 22999,
  stock: 19,
  rating: 4.4,
},
{
  name: "Vivo Y300",
  brand: "Vivo",
  category: "Smartphones",
  condition: "new",
  description: "Modern Vivo smartphone for everyday performance and entertainment.",
  price: 21999,
  originalPrice: 24999,
  stock: 15,
  rating: 4.5,
},
{
  name: "iPhone 18 Pro",
  brand: "Apple",
  category: "Smartphones",
  condition: "new",
  description: "Latest Apple Pro smartphone with advanced camera system, premium design, and high-performance hardware.",
  price: 164900,
  originalPrice: 164900,
  stock: 8,
  rating: 4.9,
  image: "/uploads/products/iphone-18-pro.jpg",
},
];

const seedProducts = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);

    console.log("MongoDB connected");

    let added = 0;
    let skipped = 0;

    for (const product of products) {
      const exists = await Product.findOne({ name: product.name });

     if (exists) {
  await Product.findByIdAndUpdate(
    exists._id,
    { image: "" },
    { new: true }
  );

  skipped++;
  continue;
}

      await Product.create(product);
      added++;
      console.log(`Added: ${product.name}`);
    }

    console.log(`\nCatalog seeding completed`);
    console.log(`Added: ${added}`);
    console.log(`Skipped existing: ${skipped}`);

    await mongoose.disconnect();
    process.exit(0);
  } catch (error) {
    console.error("Catalog seeding failed:", error.message);
    await mongoose.disconnect();
    process.exit(1);
  }
};

seedProducts();